### PR TITLE
icarus-rtl-jalaali

### PR DESCRIPTION
**Pull request by ghaseminya**

### CODE REVIEW

**Comment by ppoffice** [comment]
@ghaseminya 
Thank you for this PR, but the commit history in this PR looks rather confusing... Would you please fork this repo and `rebase` new features on top?

**Comment by ghaseminya** [comment]
@ppoffice 
Yes...this is better way...

**Comment by ppoffice** [comment]
@ghaseminya 
Sorry to interrupt, but I think `jalaali calendar` is an enhancing feature that requires external libraries to be installed in the blog's root. I think a tutorial or a branch repo is enough as a reference. What do you think?

**Comment by ghaseminya** [comment]
Yes...
I fork to my repo and create a tutorial about how to add jalaali and rtl support in README. Is it good?

**Comment by ppoffice** [comment]
I appreciate that you fork this repo and keep working on RTL language localizations 😄, this is also convenient for RTL language users to collaborate.

**Comment by ghaseminya** [comment]
Sure..
I think some changes must be affected to create a complete RTL version...
https://github.com/ghaseminya/hexo-theme-icarus_rtl_jalaali

**Comment by ghaseminya** [comment]
create direct fork from your repo? or create new project like above link?

**Comment by ppoffice** [comment]
Fork the hueman-theme-icarus repo

**Comment by ghaseminya** [comment]
https://github.com/ghaseminya/hexo-theme-icarus_rtl_jalaali

**Pull request closed without merging**
