### PR TITLE
Spanish + Google Websmaster tools + More speed in loading page for America and Europe

### PR DESCRIPTION
**Pull request by srwooow**
Hi!
(sorry for my bad english)
- Added Spanish
- Added Google Websmater tools support
- More speed in loading page for America and Europe
  - I changed all scripts and fonts from "useso.com" for the google host, See the diference in the page loading time:
(Useso is good for china but outside it is very slow)

925295433f4442a74d1cf77eb6a0cd83

### CODE REVIEW

**Comment by ppoffice** [comment]
Google services are banned in some countries, so I have to use useso cdn instead of Google's :(
Translations are welcomed :)

**Comment by srwooow** [comment]
And if we use adobe fonts (https://edgewebfonts.adobe.com/fonts) and cdnjs for the 
jquery.min.js (https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js)?

**Comment by ppoffice** [comment]
I'm sorry but I have to admit that Adobe web fonts are too slow here. I created a new branch `google-cdn`, you can split the pull request into two parts and push the CDN part into that branch.

**Comment by ppoffice** [comment]
Or you can just add a config to let users choose what CDN they want to use:)

**Comment by srwooow** [comment]
Okay, with this new code users can change the CND :)

**Pull request merged**
