### PR TITLE
feat(layout): add customization of article licensing block

### PR DESCRIPTION
**Pull request by Kitcham**
## Commit Message
feat(layout): add customization of article licensing block

## Commit Body
The feature allows users to customize invisibility of licensing block in specific pages.

该功能允许用户自定义是否於特定页面隐藏许可协议。

## Demo
Licensing block will be shown by default. Users may use front-matter below to hide licensing block.
```yaml
title: Icarus User Guide - Configuring the Theme
…
hide_license: true
…
---

### CODE REVIEW

**Comment by ppoffice** [comment]
@Kitcham You can hide this block by just deleting all licenses. There's no need to add a flag for it.

**Comment by Kitcham** [comment]
@ppoffice In some case, it is a useful feature:
- Some pages/articles posted by another license
- Some pages for specific use(bbs, links and so on), license should be hidden

If you think there's no need to add the flag, I would close this PR.

**Comment by ppoffice** [comment]
@Kitcham My opinion is that Icarus should _provide basic functions_ that can are _easy to use out-of-the-box_ while _keeping the configuration complexity manageable_. Since you can turn off or override licenses in the front-matter, adding a dedicated flag would be less useful:

You can override licenses in the front-matter like this:

```yaml
article:
    # ...your other article configurations...
    licenses: # leave empty to turn off license block
---
# article content
```

**Comment by Kitcham** [comment]
That's a better sollution. I will close this PR

**Pull request closed without merging**
