### PR TITLE
Add the "top" icon before the title of article

### PR DESCRIPTION
**Pull request by charjindev**
## Add the "top" icon before the title of article if the property "top" is true or an integer (>0) at the front-matter
add top icon

### CODE REVIEW

**Comment by ppoffice** [comment]
@charjindev Icarus does not have the "pin on top" feature right now. This "top" icon does not make sense until that feature is available. Pull requests on "pin an article on top" will be appreciated.

**Comment by charjindev** [comment]
> @charjindev Icarus does not have the "pin on top" feature right now. This "top" icon does not make sense until that feature is available. Pull requests on "pin an article on top" will be appreciated.  

Screen Shot 2019-07-12 at 14 35 59
Thanks for your reply. Certainly, don't mention the "pin to top" feature in your tutorial and instruction.  But it can do works. As you can see from the picture above, I set the "top" at the beginning of the "posts" actually and the article really pins the top of list.  Haha, maybe it makes sense.

**Comment by jitwxs** [comment]
This is not useful...

**Comment by ppoffice** [comment]
@charjindev Are you using this Hexo plugin? 
https://github.com/netcan/hexo-generator-index-pin-top

**Comment by WhenCoding** [comment]
> @charjindev Are you using this Hexo plugin?
> https://github.com/netcan/hexo-generator-index-pin-top

use it replace 'hexo-generator-index' can ok.

**Pull request closed without merging**
